python:
  - 3.7
  - 3.8
  - 3.9
  - 3.10

pin_run_as_build:
  python: x.x.x
  py4j: x.x.x
  nomkl: x.x.x
  pandas: x.x.x
  python-dateutil: x.x.x
  numpy: x.x.x
  pyarrow: x.x.x
  jpype1: x.x.x


version_number:
  - 0 # Increment this whenever you make changes