package:
  name: knime-python-base
  version: "4.6.0"

requirements:
  run:
    - python {{ python }}
    - py4j
    - nomkl
    - pandas
    - python-dateutil
    - numpy
    - cairo
    - pillow
    - matplotlib
    - pyarrow 7.*
    - IPython
    - nbformat
    - scipy
    - jpype1



build:
  number: {{ version_number }}
  string: py{{ python | replace(".", "") }}_{{ version_number }}
  pin_depends: strict


test:
  imports:
    - pyarrow
    - pandas

about:
  home: https://knime.com
  license: GPL-3.0
