package:
  name: knime-python-scripting
  version: "4.6.0"

requirements:
  build:
    - python {{ python }}
    - cairo
    - pillow
    - matplotlib
    - ipython
    - nbformat
    - scipy
    - jedi
    - knime-python-base

  run:
    - python                # Python
    - cairo                 # SVG support
    - pillow                # Image inputs/outputs
    - matplotlib            # Plotting
    - ipython               # Notebook support
    - nbformat              # Notebook support
    - scipy                 # Notebook support
    - jedi                  # Python script autocompletion
    - knime-python-base     # Basic packages needed to use python in KNIME

test:
  imports:
    - ipython
    - jedi

build:
  number: {{ version_number }}
  string: py{{ python | replace(".", "") }}_{{ version_number }}

about:
  home: https://knime.com
  license: GPL-3.0
  license_file: LICENSE.TXT
  summary: The knime-python-scripting package combines all dependencies needed to use the Python Scripting nodes in the KNIME Analytics Platform.
