package:
  name: knime-python-scripting
  version: "4.6.0"

requirements:
  run:
    - jedi # Autocompletion, static analysis and refactoring library
    - knime-python-base # Basic packages needed to use python in KNIME

build:
  number: {{ version_number }}
  string: {{ version_number }}

about:
  home: https://knime.com
  license: GPL-3.0
