# build with 
# conda build . --python 3.9 -c conda-forge --override-channels --prefix-length 150
package:
  name: knime-python-base
  version: "4.6"

requirements:
  run:
    - python
    - py4j
    - numpy
    - pandas
    - pyarrow=6.0
    - jedi

about:
  home: https://knime.com
  license: GPL-3.0
