#package:
#  name: knime-python-dl
#  version: "4.6.0"
# TODO
#requirements:
#  run:
#    - tensorflow-mkl w1.15
#    - tensorflow-estimator=1.15 # or mac will install 2.6 which doesn't work
#    - tensorflow-hub
#    - keras 2.2.4
#    - python-flatbuffers <2.0 [py>=39] # TODO needed for tensorflow, move to tf meta yaml??
#    - h5py <3.0
#    - protobuf >3.12 [py>=38] # TODO needed for tensorflow, move to tf meta yaml??

#### TODO 
#### Extra dependencies from Windows/py37_knime_dl_cpu. 
### Is there sth to think about? Why is there no dl for py38/39?
### Why is there no tl for py37?
#build:
#  number: 2
#  string: abc

#about:
#  home: https://knime.com
#  license: GPL-3.0
