package:
  name: knime-mdf
  version: "4.6.0"

requirements:
  build:
    - libiconv
  run:
    - knime-python-base     # Basic packages needed to use python in KNIME
    - libiconv              # Is already installed because of knime-python-base, but we will still keep it here for the sake of completeness
    - asammdf 5.19.14       # MDF node

build:
  number: {{ version_number }}
  string: {{ version_number }}

about:
  home: https://knime.com
  license: GPL-3.0
  license_file: LICENSE.TXT
  summary: The knime-mdf package combines all dependencies needed to use the MDF Reader node in the KNIME Analytics Platform
