package:
  name: knime-mdf
  version: "4.6.0"

requirements:
  run:
    - libiconv # Is already installed because of knime-python-base, but we will still keep it here for the sake of completeness
    - asammdf 5.19.14
    - knime-python-base # Basic packages needed to use python in KNIME

build:
  number: {{ version_number }}
  string: {{ version_number }}

about:
  home: https://knime.com
  license: GPL-3.0
